version: "{build}-{branch}"

environment:
  matrix:
    - job_name: macOS XCode 9
      APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - job_name: macOS XCode 10
      APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - job_name: macOS XCode 11
      APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - job_name: macOS XCode 12
      APPVEYOR_BUILD_WORKER_IMAGE: macOS

for:
  - matrix:
      only:
        - job_name: macOS XCode 9
    install:
      - sudo xcode-select -s /Applications/Xcode-9.4.1.app
  - matrix:
      only:
        - job_name: macOS XCode 10
    install:
      - sudo xcode-select -s /Applications/Xcode-10.3.app
  - matrix:
      only:
        - job_name: macOS XCode 11
    install:
      - sudo xcode-select -s /Applications/Xcode-11.7.app
  - matrix:
      only:
        - job_name: macOS XCode 12
    install:
      - sudo xcode-select -s /Applications/Xcode-12.3.app

configuration:
  - Debug

before_build:
  - ps: gci env:* | sort-object name
  - cmake --version
  - cmd: cmake -B build -D CMAKE_BUILD_TYPE=%CONFIGURATION% -A %PLATFORM%
  - sh: cmake -B build -D CMAKE_BUILD_TYPE=${CONFIGURATION}

build_script:
  - cmd: cmake --build build --config %CONFIGURATION% -j %NUMBER_OF_PROCESSORS%
  - sh: cmake --build build --config ${CONFIGURATION} -j $(nproc)

test_script:
  - cd build
  - cmd: ctest -C %CONFIGURATION% -j %NUMBER_OF_PROCESSORS%
  - sh: ctest -C ${CONFIGURATION} -j $(nproc)
