language: cpp
dist: xenial
compiler: gcc

os:
  - linux

branches:
  only:
  - master

before_script:
  - printenv
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build && cmake --build . --parallel 2 --clean-first --config Debug && ctest .
  - cd $TRAVIS_BUILD_DIR/build && cmake --build . --parallel 2 --clean-first --config Release && ctest .

notifications:
  email: false