language: cpp

dist: xenial

compiler:
  - clang
  - gcc

os:
  - linux

branches:
  only:
  - master

before_script:
  - printenv
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build && cmake --build . --config Debug -j2 && ctest .
  - cd $TRAVIS_BUILD_DIR/build && cmake --build . --config Release -j2 && ctest .

notifications:
  email: false