dist: xenial
sudo: required
language: cpp
compiler: gcc

os:
  - linux

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "M4gVCIIVDcPFlfe1SMoMG1Uz6Y1Qy6Q6Zl35QHNjYYgUjxShcvoWBW9CTtdoX2Dd3HsaklleZ7Q+vw3x4GkOW7g6se+gNJ6oyJ8nxgkxRw9/kWSpXGMEBy297M5oITrvRm7vEUOBisT+kXtYOBtbO5RtbQhG1+4VBJBvFdJic2HGAftAnht0aFywa6jkJWnzhD7JZsCUBH6Bx0C9r+94EspMFxrtOj7eas7PVCbS92GHfKYb0ZtHIkvUSf4o23ACup2171toktDYkdxG3EKxb4bETN3keFU7WGsuYjnh0QQtVKiwdyV8Qk+XsXV7BnM+03Yb5YgEmbiGNhT87iMQD3F7H1Bb7dKWQKHm/cZqGjdLY+nAWaG+E728eHuc7OMPHrjDjkctuc2cNegFlZSgb0vIIojZImWKOVBfXSSf/ahcCdavzJrM2asCGP/ZBdyp1Pqa1+zPvre4lUr3tcr9qMqGoRk7qJ7msSMEqRSKpjLJ5Nppgf2TK7u5vp7fXO7xZ6VI9PLF1qrOHUxsA730yUnB6tAtyQvGPV45pDUDYI05CsuZHLhAwApkdWFfBUX+4CkQKkSBuNqhCfdHk52b3llU21j2zVa2yX1qSKRkBeOMt578otKWMH/ycrWY3MgoWZDm3Mp0BWPkEPvNxSRthYI3RCowBJ5zJ4IK9Ui/tHs="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "KibaAmor/knet"
      description: "A cross platform lock-free and timer-supported(hearbeat etc.) C++11 network library."
    notification_email: kibaamor@gmail.com
    build_command_prepend: "mkdir -p $TRAVIS_BUILD_DIR/coverity_scan && cd $TRAVIS_BUILD_DIR/coverity_scan && cmake .."
    build_command: "cd $TRAVIS_BUILD_DIR/coverity_scan && cmake --build . --parallel 2 --config Release"
    branch_pattern: coverity_scan

before_script:
  - printenv
  - mkdir -p $TRAVIS_BUILD_DIR/build_debug && cd $TRAVIS_BUILD_DIR/build_debug && cmake ..
  - mkdir -p $TRAVIS_BUILD_DIR/build_release && cd $TRAVIS_BUILD_DIR/build_release && cmake ..

script:
  - cd $TRAVIS_BUILD_DIR/build_debug && cmake --build . --parallel 2 --clean-first --config Debug && ctest .
  - cd $TRAVIS_BUILD_DIR/build_release && cmake --build . --parallel 2 --clean-first --config Release && ctest .

notifications:
  email: false