version: '{build}'

branches:
  only:
    - master

max_jobs: 16

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

matrix:
  fast_finish: true

platform:
  - Win32
  - x64
  
configuration:
  - Debug
  - Release

before_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake --version
  - cmd: cmake .. -A %PLATFORM%

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: cmake --build . --config %CONFIGURATION% --target ALL_BUILD

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: ctest -C %CONFIGURATION%
