version: '{build}'

branches:
  only:
    - master

max_jobs: 16

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

clone_folder: c:\projects\knet

matrix:
  fast_finish: true

platform:
  - Win32
  - x64
  
configuration:
  - Debug
  - Release

init:
  - set arch=
  - if "%PLATFORM%"=="x64" ( set arch= x64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - echo %generator%
  
before_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake --version
  - cmd: cmake .. -G %generator% -DCMAKE_BUILD_TYPE=%CONFIGURATION%

build:
  parallel: true
  project: c:\projects\knet\build\knet.sln

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: ctest -C %CONFIGURATION%
