version: "{build}"

environment:
  matrix:
    - job_name: Visual Studio 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      job_group: Windows build
    - job_name: Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      job_group: Windows build
    - job_name: Visual Studio 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      job_group: Windows build

    - job_name: Ubuntu GCC 5
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      job_group: Linux build
    - job_name: Ubuntu GCC 6
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      job_group: Linux build
    - job_name: Ubuntu GCC 7
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      job_group: Linux build
    - job_name: Ubuntu GCC 8
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      job_group: Linux build
    - job_name: Ubuntu GCC 9
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      job_group: Linux build

    - job_name: macOS XCode 9
      APPVEYOR_BUILD_WORKER_IMAGE: macos
      job_group: macOS build
    - job_name: macOS XCode 10
      APPVEYOR_BUILD_WORKER_IMAGE: macos
      job_group: macOS build
    - job_name: macOS XCode 11
      APPVEYOR_BUILD_WORKER_IMAGE: macos
      job_group: macOS build
    - job_name: macOS XCode 12
      APPVEYOR_BUILD_WORKER_IMAGE: macos
      job_group: macOS build

matrix:
  fast_finish: true

for:
  - matrix:
      only:
        - job_group: Windows build

  - matrix:
      only:
        - job_name: Ubuntu GCC 5
    environment:
      CC: gcc-5
      CXX: g++-5
  - matrix:
      only:
        - job_name: Ubuntu GCC 6
    environment:
      CC: gcc-6
      CXX: g++-6
  - matrix:
      only:
        - job_name: Ubuntu GCC 7
    environment:
      CC: gcc-7
      CXX: g++-7
  - matrix:
      only:
        - job_name: Ubuntu GCC 8
    environment:
      CC: gcc-8
      CXX: g++-8
  - matrix:
      only:
        - job_name: Ubuntu GCC 9
    environment:
      CC: gcc-9
      CXX: g++-9

  - matrix:
      only:
        - job_name: macOS XCode 9
    init:
      - xcode-select -switch /Applications/Xcode_9.4.1.app
  - matrix:
      only:
        - job_name: macOS XCode 10
    init:
      - xcode-select -switch /Applications/Xcode_10.3.app
  - matrix:
      only:
        - job_name: macOS XCode 11
    init:
      - xcode-select -switch /Applications/Xcode_11.7.app
  - matrix:
      only:
        - job_name: macOS XCode 12
    init:
      - xcode-select -switch /Applications/Xcode_12.3.app

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release
  - MinSizeRel
  - RelWithDebInfo

before_build:
  - ps: cmake --version
  - ps: cd ${env:APPVEYOR_BUILD_FOLDER}
  - cmd: cmake . -B build -A %PLATFORM%
  - sh: cmake . -B build

build_script:
  - ps: cd ${env:APPVEYOR_BUILD_FOLDER}
  - ps: cmake --build build --config ${env:CONFIGURATION}

test_script:
  - ps: cd ${env:APPVEYOR_BUILD_FOLDER}/build
  - ps: ctest -C ${env:CONFIGURATION}
