version: '{build}'

branches:
  only:
    - master

max_jobs: 16

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

clone_folder: c:\projects\knet

matrix:
  fast_finish: true

platform:
  - x86
  - x64
  
configuration:
  - Debug
  - Release

init:
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
  - echo %generator%
  
before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake --version
  - cmd: cmake .. -G %generator%

build:
  parallel: true
  project: c:\projects\knet\build\knet.sln