version: "{build}"

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

matrix:
  fast_finish: true

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: cmake --version
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: cmake . -B build -A %PLATFORM%

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: cmake --build build --config %CONFIGURATION%

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build
  - cmd: ctest -C %CONFIGURATION%
